# -*- coding: utf-8 -*-
"""01_processamento_calculo_indicadores.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pti1rAt94SDuBaeGRn1GESwPBQqjdNsw
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile 01_processamento_calculo_indicadores.py
# 
# # Script 01 – Processamento e Cálculo dos Indicadores Financeiros
# # Este script realiza a extração, o tratamento e o cálculo dos indicadores
# # ROA, ROE e Margem Líquida a partir das Demonstrações Financeiras Padronizadas
# # (DFPs) disponibilizadas pela Comissão de Valores Mobiliários (CVM).
# # Produto final: indicadores_calculados.csv
# 
# import requests
# import zipfile
# import io
# import pandas as pd
# import sqlite3
# from google.colab import files
# 
# # 1. URL do site da CVM
# url = "http://dados.cvm.gov.br/dados/CIA_ABERTA/DOC/DFP/DADOS/dfp_cia_aberta_2024.zip"
# 
# # 2. Baixar o arquivo .zip
# print("🔽 Baixando arquivo ZIP da CVM...")
# response = requests.get(url)
# if response.status_code == 200:
#     print("✔ Download concluído!")
# else:
#     raise Exception("Erro no download do arquivo da CVM.")
# 
# # 3. Abrir o arquivo .zip
# with zipfile.ZipFile(io.BytesIO(response.content)) as z:
#     # --- DRE ---
#     target_dre = "dfp_cia_aberta_DRE_con_2024.csv"
#     if target_dre in z.namelist():
#         with z.open(target_dre) as f:
#             dre = pd.read_csv(f, sep=";", encoding="latin1", dtype=str)
#     else:
#         raise Exception(f"{target_dre} não encontrado no ZIP.")
# 
#     # --- BPA ---
#     target_bpa = "dfp_cia_aberta_BPA_con_2024.csv"
#     if target_bpa in z.namelist():
#         with z.open(target_bpa) as f:
#             bpa = pd.read_csv(f, sep=";", encoding="latin1", dtype=str)
#     else:
#         raise Exception(f"{target_bpa} não encontrado no ZIP.")
# 
#     # --- BPP ---
#     target_bpp = "dfp_cia_aberta_BPP_con_2024.csv"
#     if target_bpp in z.namelist():
#         with z.open(target_bpp) as f:
#             bpp = pd.read_csv(f, sep=";", encoding="latin1", dtype=str)
#     else:
#         raise Exception(f"{target_bpp} não encontrado no ZIP.")
# 
# # 4. Filtrar Lucro Líquido (CD_CONTA = '3.11') na DRE
# dre_filtrado = dre[dre["CD_CONTA"] == "3.11"]
# dre_filtrado = dre_filtrado[["CNPJ_CIA", "DENOM_CIA", "ORDEM_EXERC", "VL_CONTA"]]
# dre_filtrado["VL_CONTA"] = pd.to_numeric(dre_filtrado["VL_CONTA"], errors="coerce")
# 
# # 5. Filtrar Receita Total (CD_CONTA = '3.01') na DRE
# dre_receita = dre[dre["CD_CONTA"] == "3.01"]
# dre_receita = dre_receita[["CNPJ_CIA", "ORDEM_EXERC", "VL_CONTA"]]
# dre_receita["VL_CONTA"] = pd.to_numeric(dre_receita["VL_CONTA"], errors="coerce")
# 
# # 6. Filtrar Ativo Total (CD_CONTA = '1') no BPA
# bpa_filtrado = bpa[bpa["CD_CONTA"] == "1"]
# bpa_filtrado = bpa_filtrado[["CNPJ_CIA", "ORDEM_EXERC", "VL_CONTA"]]
# bpa_filtrado["VL_CONTA"] = pd.to_numeric(bpa_filtrado["VL_CONTA"], errors="coerce")
# 
# # 7. Filtrar Patrimônio Líquido pelo DS_CONTA no BPP
# bpp_filtrado = bpp[bpp["DS_CONTA"] == "Patrimônio Líquido Consolidado"]
# bpp_filtrado = bpp_filtrado[["CNPJ_CIA", "ORDEM_EXERC", "VL_CONTA"]]
# bpp_filtrado["VL_CONTA"] = pd.to_numeric(bpp_filtrado["VL_CONTA"], errors="coerce")
# 
# # 8. Criar banco de dados SQLite e salvar tabelas
# conn = sqlite3.connect("dfp_empresas.db")
# dre_filtrado.to_sql("lucro_liquido", conn, if_exists="replace", index=False)
# dre_receita.to_sql("receita_total", conn, if_exists="replace", index=False)
# bpa_filtrado.to_sql("ativo_total", conn, if_exists="replace", index=False)
# bpp_filtrado.to_sql("patrimonio_liquido", conn, if_exists="replace", index=False)
# print("✔ Banco de dados criado com sucesso: dfp_empresas.db")
# 
# # 9. Consulta consolidada com nomes de colunas finais (Ano_2023 e Ano_2024)
# query = """
# SELECT l.CNPJ_CIA,
#        MAX(l.DENOM_CIA) AS DENOM_CIA,
#        MAX(CASE WHEN l.ORDEM_EXERC = 'PENÚLTIMO' THEN l.VL_CONTA END) AS Lucro_Ano_2023,
#        MAX(CASE WHEN l.ORDEM_EXERC = 'ÚLTIMO' THEN l.VL_CONTA END) AS Lucro_Ano_2024,
#        MAX(CASE WHEN r.ORDEM_EXERC = 'PENÚLTIMO' THEN r.VL_CONTA END) AS Receita_Ano_2023,
#        MAX(CASE WHEN r.ORDEM_EXERC = 'ÚLTIMO' THEN r.VL_CONTA END) AS Receita_Ano_2024,
#        MAX(CASE WHEN a.ORDEM_EXERC = 'PENÚLTIMO' THEN a.VL_CONTA END) AS Ativo_Ano_2023,
#        MAX(CASE WHEN a.ORDEM_EXERC = 'ÚLTIMO' THEN a.VL_CONTA END) AS Ativo_Ano_2024,
#        MAX(CASE WHEN p.ORDEM_EXERC = 'PENÚLTIMO' THEN p.VL_CONTA END) AS PL_Ano_2023,
#        MAX(CASE WHEN p.ORDEM_EXERC = 'ÚLTIMO' THEN p.VL_CONTA END) AS PL_Ano_2024
# FROM lucro_liquido l
# LEFT JOIN receita_total r
#        ON l.CNPJ_CIA = r.CNPJ_CIA
# LEFT JOIN ativo_total a
#        ON l.CNPJ_CIA = a.CNPJ_CIA
# LEFT JOIN patrimonio_liquido p
#        ON l.CNPJ_CIA = p.CNPJ_CIA
# GROUP BY l.CNPJ_CIA;
# """
# df_resultado = pd.read_sql_query(query, conn)
# print("\n📊 Resultado consolidado (amostra):")
# print(df_resultado.head())
# conn.close()
# 
# # 10. Upload da lista de empresas no Colab
# print("\n📂 Faça o upload do arquivo lista_empresas.csv")
# uploaded = files.upload()
# empresas_lista = pd.read_csv("lista_empresas.csv", dtype=str, encoding="latin1", sep=';')  # deve conter colunas "CNPJ" e "setor"
# 
# # 11. Filtrar o dataframe principal
# df_empresas_filtradas = df_resultado[df_resultado["CNPJ_CIA"].isin(empresas_lista["CNPJ"])]
# 
# # 12. Identificar CNPJs não encontrados
# cnpjs_nao_encontrados = set(empresas_lista["CNPJ"]) - set(df_resultado["CNPJ_CIA"])
# print(f"\n⚠️ Empresas da lista que não foram encontradas na base da CVM: {len(cnpjs_nao_encontrados)}")
# if cnpjs_nao_encontrados:
#     print(cnpjs_nao_encontrados)
# 
# # 13. Criar novo banco só com as empresas filtradas
# conn2 = sqlite3.connect("dfp_empresas_filtradas.db")
# df_empresas_filtradas.to_sql("dados_filtrados", conn2, if_exists="replace", index=False)
# conn2.close()
# print("✔ Novo banco criado com sucesso: dfp_empresas_filtradas.db")
# print(f"📊 Número de empresas filtradas: {len(df_empresas_filtradas)}")
# 
# # 14. Calcular indicadores financeiros (ROA, ROE, Margem Líquida) em %
# df_indicadores = df_empresas_filtradas.copy()
# for col in ["Ativo_Ano_2023", "Ativo_Ano_2024", "PL_Ano_2023", "PL_Ano_2024", "Receita_Ano_2023", "Receita_Ano_2024"]:
#     df_indicadores[col].replace(0, pd.NA, inplace=True)
# 
# df_indicadores["ROA_Ano_2023"] = (df_indicadores["Lucro_Ano_2023"] / df_indicadores["Ativo_Ano_2023"]) * 100
# df_indicadores["ROA_Ano_2024"] = (df_indicadores["Lucro_Ano_2024"] / df_indicadores["Ativo_Ano_2024"]) * 100
# df_indicadores["ROE_Ano_2023"] = (df_indicadores["Lucro_Ano_2023"] / df_indicadores["PL_Ano_2023"]) * 100
# df_indicadores["ROE_Ano_2024"] = (df_indicadores["Lucro_Ano_2024"] / df_indicadores["PL_Ano_2024"]) * 100
# df_indicadores["Margem_Liquida_Ano_2023"] = (df_indicadores["Lucro_Ano_2023"] / df_indicadores["Receita_Ano_2023"]) * 100
# df_indicadores["Margem_Liquida_Ano_2024"] = (df_indicadores["Lucro_Ano_2024"] / df_indicadores["Receita_Ano_2024"]) * 100
# 
# cols_arredondar = ["ROA_Ano_2023","ROA_Ano_2024","ROE_Ano_2023","ROE_Ano_2024",
#                    "Margem_Liquida_Ano_2023","Margem_Liquida_Ano_2024"]
# df_indicadores[cols_arredondar] = df_indicadores[cols_arredondar].round(2)
# 
# # 15. Adicionar coluna "setor" da lista de empresas
# df_indicadores = df_indicadores.merge(empresas_lista[['CNPJ','SETOR']],
#                                       left_on='CNPJ_CIA', right_on='CNPJ', how='left')
# df_indicadores.drop(columns=['CNPJ'], inplace=True)
# 
# # 16. Criar novo banco de dados com os indicadores calculados (SQLite)
# conn3 = sqlite3.connect("indicadores_calculados.db")
# df_indicadores.to_sql("indicadores_calculados", conn3, if_exists="replace", index=False)
# conn3.close()
# print("✔ Novo banco criado com sucesso: indicadores_calculados.db")
# 
# # 17. Exportar indicadores calculados para CSV
# csv_filename = "indicadores_calculados.csv"
# df_indicadores.to_csv(csv_filename, index=False, sep=';', encoding='latin1')
# print(f"✔ CSV criado com sucesso: {csv_filename}")
# files.download(csv_filename)
# 
# # 18. Criar CSV para dashboard em formato long
# df_dashboard = pd.wide_to_long(df_indicadores,
#                                stubnames=['Lucro_Ano','Ativo_Ano','PL_Ano','Receita_Ano',
#                                           'ROA_Ano','ROE_Ano','Margem_Liquida_Ano'],
#                                i=['CNPJ_CIA','DENOM_CIA','SETOR'],
#                                j='Ano', sep='_', suffix='.+').reset_index()
# 
# # Ajustar valores da coluna Ano para 2023/2024
# df_dashboard['Ano'] = df_dashboard['Ano'].astype(int)
# 
# # Renomear colunas para simplificar
# df_dashboard.rename(columns={
#     'Lucro_Ano':'Lucro',
#     'Ativo_Ano':'Ativo',
#     'PL_Ano':'PL',
#     'Receita_Ano':'Receita',
#     'ROA_Ano':'ROA',
#     'ROE_Ano':'ROE',
#     'Margem_Liquida_Ano':'Margem_Liquida'
# }, inplace=True)
# 
# # Exportar CSV para dashboard
# csv_dashboard = "indicadores_dashboard.csv"
# df_dashboard.to_csv(csv_dashboard, index=False, sep=';', encoding='latin1')
# print(f"✔ CSV para dashboard criado com sucesso: {csv_dashboard}")
# files.download(csv_dashboard)
# 
# print("\n📊 Amostra do CSV para dashboard:")
# print(df_dashboard.head())
#