# -*- coding: utf-8 -*-
"""02_analise_estatistica_visualizacao.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SQGPDAG_VxgqLg1eNLxxVEtDLrZ-NS9z
"""

# Commented out IPython magic to ensure Python compatibility.
# 
# %%writefile 02_analise_estatistica_visualizacao.py
# 
# #Script 02 – Análise Estatística e Visualização dos Dados
# #Este script realiza a análise estatística exploratória e inferencial dos indicadores financeiros calculados, incluindo estatísticas descritivas,
# #análise de distribuição, correlação de Pearson, teste t pareado e teste
# #não paramétrico de Wilcoxon, além de visualizações gráficas.
# 
# # 1. Importar bibliotecas
# import pandas as pd
# import matplotlib.pyplot as plt
# from scipy.stats import shapiro, ttest_rel, pearsonr, wilcoxon
# from google.colab import files
# 
# plt.rcParams['figure.figsize'] = (7, 4)
# 
# # 2. Upload do CSV
# print("📁 Faça o upload do arquivo 'indicadores_calculados.csv'")
# uploaded = files.upload()
# file_name = list(uploaded.keys())[0]
# df = pd.read_csv(file_name, sep=';', encoding='latin1')
# 
# # 3. Indicadores analisados
# indicadores = {
#     "ROA": ("ROA_Ano_2023", "ROA_Ano_2024"),
#     "ROE": ("ROE_Ano_2023", "ROE_Ano_2024"),
#     "Margem_Liquida": ("Margem_Liquida_Ano_2023", "Margem_Liquida_Ano_2024")
# }
# 
# # 4. Estatísticas descritivas
# print("\n📊 Estatísticas Descritivas")
# for ind, (c23, c24) in indicadores.items():
#     stats = df[[c23, c24]].agg(['mean', 'median', 'std']).round(3)
#     print(f"\nIndicador: {ind}")
#     display(stats)
# 
# # 4.1 Histogramas – Distribuição de Frequências dos Indicadores
# print("\n📊 Histogramas – Distribuição de Frequências")
# 
# for ind, (c23, c24) in indicadores.items():
#     plt.figure()
# 
#     plt.hist(
#         df[c23].dropna(),
#         bins=10,
#         color='lightgray',
#         edgecolor='black',
#         alpha=0.7,
#         label='2023'
#     )
# 
#     plt.hist(
#         df[c24].dropna(),
#         bins=10,
#         color='dimgray',
#         edgecolor='black',
#         alpha=0.7,
#         label='2024'
#     )
# 
#     plt.title(f"Distribuição de Frequências – {ind}")
#     plt.xlabel(f"{ind} (%)")
#     plt.ylabel("Frequência")
#     plt.legend()
#     plt.grid(axis='y', linestyle='--', alpha=0.4)
# 
#     plt.show()
# 
# # 5. Teste de normalidade (Shapiro-Wilk) nas diferenças
# print("\n📈 Teste de Normalidade (Shapiro-Wilk)")
# normalidade = {}
# 
# for ind, (c23, c24) in indicadores.items():
#     diff = df[c24] - df[c23]
#     stat, p = shapiro(diff.dropna())
#     normalidade[ind] = p
#     print(f"{ind}: p-value = {p:.4f} → {'Normal' if p > 0.05 else 'Não normal'}")
# 
# # 6. Teste t de Student pareado
# print("\n📊 Teste t de Student Pareado")
# resultados_t = []
# 
# for ind, (c23, c24) in indicadores.items():
#     t_stat, p_val = ttest_rel(df[c24], df[c23], nan_policy='omit')
#     resultados_t.append([ind, t_stat, p_val])
# 
#     print(f"\nIndicador: {ind}")
#     print(f"t = {t_stat:.3f} | p-value = {p_val:.4f}")
#     if p_val < 0.05:
#         print("→ Diferença estatisticamente significativa (p < 0.05)")
#     else:
#         print("→ Diferença não significativa (p ≥ 0.05)")
# 
# # 6.1 Teste de Wilcoxon Pareado (análise de robustez)
# print("\n📊 Teste de Wilcoxon Pareado (Robustez)")
# 
# resultados_wilcoxon = []
# 
# for ind, (c23, c24) in indicadores.items():
#     # Remover pares com valores ausentes
#     dados_pareados = df[[c23, c24]].dropna()
# 
#     # O Wilcoxon exige pelo menos um par não nulo
#     if len(dados_pareados) > 0:
#         stat, p_val = wilcoxon(
#             dados_pareados[c24],
#             dados_pareados[c23]
#         )
# 
#         resultados_wilcoxon.append([ind, stat, p_val])
# 
#         print(f"\nIndicador: {ind}")
#         print(f"Estatística W = {stat:.3f} | p-value = {p_val:.4f}")
# 
#         if p_val < 0.05:
#             print("→ Diferença estatisticamente significativa (p < 0.05)")
#         else:
#             print("→ Diferença não significativa (p ≥ 0.05)")
# 
# # 6.2 Tabela resumo – Teste de Wilcoxon
# df_wilcoxon = pd.DataFrame(
#     resultados_wilcoxon,
#     columns=["Indicador", "Estatística W", "p-value"]
# ).round(4)
# 
# print("\n📋 Resumo dos Testes de Wilcoxon")
# display(df_wilcoxon)
# 
# # 7. Tabela resumo dos testes
# df_resultados = pd.DataFrame(
#     resultados_t,
#     columns=["Indicador", "Estatística t", "p-value"]
# ).round(4)
# 
# print("\n📋 Resumo dos Testes t")
# display(df_resultados)
# 
# # 8. Correlação de Pearson (valores reais) – 2023 e 2024
# print("\n📊 Correlação de Pearson – Exercício de 2023")
# 
# corr_cols_2023 = [
#     "ROA_Ano_2023",
#     "ROE_Ano_2023",
#     "Margem_Liquida_Ano_2023"
# ]
# 
# corr_2023 = df[corr_cols_2023].corr().round(3)
# display(corr_2023)
# 
# 
# print("\n📊 Correlação de Pearson – Exercício de 2024")
# 
# corr_cols_2024 = [
#     "ROA_Ano_2024",
#     "ROE_Ano_2024",
#     "Margem_Liquida_Ano_2024"
# ]
# 
# corr_2024 = df[corr_cols_2024].corr().round(3)
# display(corr_2024)
# 
# # 9. Gráficos (boxplot por indicador)
# for ind, (c23, c24) in indicadores.items():
#     plt.boxplot([df[c23].dropna(), df[c24].dropna()],
#                 labels=["2023", "2024"])
#     plt.title(f"{ind} – Comparação 2023 vs 2024")
#     plt.ylabel("%")
#     plt.show()
#